#####################################################################
# SILVA taxonomic training data formatted for DADA2 (Silva version 138.2)
#
#
# Author: Callahan, B. (2024). Silva taxonomic training data formatted for DADA2 (Silva version 138.2)
# [Data set]. Zenodo. https://doi.org/10.5281/zenodo.14169026
#
# Modified by: Bolívar Aponte Rolón
# Date: 2025-12-05
#
# SILVA DB source: https://www.arb-silva.de/no_cache/download/archive/release_138_2/Exports/SILVA_138.2_SSURef_NR99_tax_silva.fasta.gz
# SILVA taxonomy source: https://www.arb-silva.de/no_cache/download/archive/release_138_2/Exports/taxonomy/
#####################################################################

library("Biostrings")
library("dada2") # Should be 1.38.0


# These fastas were generated by the following commands (using the dada2 R package version 1.35.4):

in_path <- "data/input"
if (!file.exists(file.path(in_path, "databases", "SILVA"))) {
  dir.create(file.path(in_path, "databases", "SILVA"), recursive = TRUE)
}

# FASTA ----
silva_url <- "https://www.arb-silva.de/fileadmin/silva_databases/release_138_2/Exports/SILVA_138.2_SSURef_NR99_tax_silva.fasta.gz"

download.file(
  url = silva_url,
  destfile = "data/input/databases/SILVA/SILVA_138.2_SSURef_NR99_tax_silva.fasta.gz",
  method = "curl",
  mode = "wb",
  timeout = 300
)

R.utils::gunzip(
  "data/input/databases/SILVA/SILVA_138.2_SSURef_NR99_tax_silva.fasta.gz",
  remove = FALSE
)


# Taxonomy ----
silva_txt_url <- "https://www.arb-silva.de/fileadmin/silva_databases/release_138_2/Exports/taxonomy/tax_slv_ssu_138.2.txt.gz"

download.file(
  url = silva_txt_url,
  destfile = "data/input/databases/SILVA/tax_slv_ssu_138.2.txt.gz",
  method = "curl",
  mode = "wb",
  timeout = 300
)
R.utils::gunzip(
  "data/input/databases/SILVA/tax_slv_ssu_138.2.txt.gz",
  remove = FALSE
)

# makeTaxonomy ----
fn.out.spc.slv <- file.path(
  in_path,
  "databases/SILVA/silva_nr99_v138.2_toSpecies_trainset.fa"
)

dada2:::makeTaxonomyFasta_SilvaNR(
  fin = file.path(
    in_path,
    "databases/SILVA/SILVA_138.2_SSURef_NR99_tax_silva.fasta.gz"
  ),
  ftax = file.path(in_path, "databases/SILVA/tax_slv_ssu_138.2.txt"),
  fout = fn.out.spc.slv,
  include.species = TRUE
)

# fn.out.slv <- "~/Desktop/silva_nr99_v138.2_toGenus_trainset.fa.gz"
# dada2:::makeTaxonomyFasta_SilvaNR(
#   file.path(path, "SILVA_138.2_SSURef_NR99_tax_silva.fasta.gz"),
#   file.path(path, "tax_slv_ssu_138.2.txt"),
#   fn.out.slv
# )

# fn.out.aS.slv <- "~/Desktop/silva_v138.2_assignSpecies.fa.gz"
# dada2:::makeSpeciesFasta_Silva(
#   "~/tax/silva/v138_2/SILVA_138.2_SSURef_tax_silva.fasta.gz",
#   fn.out.aS.slv
# )
